opam-version: "2.0"
lib: [
  "_destdir/Users/julie12yu/ocaml_playground/hello/_opam/lib/ocaml-index/META"
  "_destdir/Users/julie12yu/ocaml_playground/hello/_opam/lib/ocaml-index/dune-package"
  "_build/install/default/lib/ocaml-index/opam"
]
bin: "_build/install/default/bin/ocaml-index"
doc: [
  "_build/install/default/doc/ocaml-index/CHANGES.md"
  "_build/install/default/doc/ocaml-index/LICENSE"
  "_build/install/default/doc/ocaml-index/README.md"
]
